---

- name: Create the application user
  user: name={{ user_name }} state=present

- name: Create the application group
  group: name={{ user_name }} system=yes state=present

- name: Add the application user to the application group
  user: name={{ user_name }} group={{ user_name }} state=present
